export const CODES = {
  //Response app success_codes
  COD_RESPONSE_SUCCESS: 200,
  COD_RESPONSE_SUCCESS_REQUEST: 0,
  COD_RESPONSE_ERROR: 1,

  //Status ID
  COD_ACTIVE_STATUS: 200,

  //Response app error codes
  COD_RESPONSE_ERROR_CREATE: 1001,
  COD_RESPONSE_ERROR_UPDATE: 1002,
  COD_RESPONSE_ERROR_DELETE: 1003,
  COD_RESPONSE_ERROR_LIST: 1004,
  COD_RESPONSE_ERROR_LOGIN: 1005,
  COD_RESPONSE_ERROR_UNAUTHORIZED: 1006,
  COD_RESPONSE_ERROR_SHOW: 1007,
  COD_INVALID_FILE: 1008,
  COD_RESPONSE_ERROR_RESET_PASSWORD: 1009,
  COD_RESPONSE_ERROR_VALIDATE: 1010,
  COD_RESPONSE_ERROR_UPLOAD_FILE: 1011,
  COD_RESPONSE_ERROR_GENERATE_FILE: 1012,
  COD_RESPONSE_ERROR_SEND_EMAIL: 1013,
  COD_RESPONSE_LOGIN_FIRST_TIME: 1014,

  //HTTP Response codes
  COD_RESPONSE_HTTP_OK: 200,
  COD_RESPONSE_HTTP_CREATED: 201,
  COD_RESPONSE_HTTP_BAD_REQUEST: 400,
  COD_RESPONSE_HTTP_UNAUTHORIZED: 401,
  COD_RESPONSE_HTTP_FORBIDDEN: 403,
  COD_RESPONSE_HTTP_NOT_FOUND: 404,
  COD_RESPONSE_HTTP_ERROR: 500,

  //DB codes
  COD_ROLES_ADMIN: "0",
  COD_ROLES_RECRUITER: "1",
  COD_ROLES_ATHLETE: "2",

  CODES_POSICIONES: {
    PORTERO: 1,
    LATERAL_DERECHO: 2,
    CENTRAL_DERECHO: 3,
    CENTRAL_IZQUIERDO: 4,
    LATERAL_IZQUIERDO: 5,
    VOLANTE_DE_MARCA: 6,
    VOLANTE_MIXTO: 7,
    VOLANTE_OFENSIVO: 8,
    EXTREMO_DERECHO: 9,
    EXTREMO_IZQUIERDO: 10,
    DELANTERO_CENTRO: 11,
  },

  CODES_HABILIDADES: {
    AGILIDAD: 1,
    AGRESIVIDAD: 2,
    ALTURA: 3,
    AMBIDIESTRO: 4,
    CABECEADOR: 5,
    CAPACIDAD_DE_REACCIÓN: 6,
    CREADOR_DE_JUGADAS: 7,
    ESTRUCTURA_FISICA: 8,
    FUERZA_DE_TIRO: 9,
    HABILIDAD_TECNICA: 10,
    JUGADOR_SOLIDO: 11,
    LIDER: 12,
    PENALES: 13,
    PERFIL_CAMBIADO: 14,
    PROVOCADOR: 15,
    RAPIDO: 16,
    RECUPERADOR: 17,
    REGATEADOR: 18,
    SAQUE_LARGO: 19,
    SAQUE_LARGO_CON_MANOS: 20,
    TIROS_LIBRES: 21,
  },
};
